"""Chunk and embed the JD files, then emit SQL for the inserts.

Used to seed the corpus without a Supabase secret key on this machine. Embedding
needs only the publishable key, because the Edge Function is public; the writes
come out as SQL you can run wherever you do have write access.

    python scripts/emit_ingest_sql.py > seed.sql

Normal ingest is `python -m rolefit.ingest`, which writes directly. This exists
for the one-off seeding case.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rolefit import supabase as sb          # noqa: E402
from rolefit.ingest import chunk            # noqa: E402

DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "data")

# Real status from the applications table. Nothing here is invented: these are
# the values that were actually recorded against each application.
OUTCOMES = {
    "Peakflo": "applied",
    "Vela": "applied",
    "Browser-Use": "to_apply",
    "Shadeform": "to_apply",
    "Weekday": "to_apply",
    "Clinikally": "to_apply",
    "Enerjazz": "to_apply",
    "SarvM-AI": "to_apply",
    "ZenTrades": "to_apply",
}


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    print("-- generated by scripts/emit_ingest_sql.py")
    for name in sorted(os.listdir(DATA)):
        if not name.endswith(".txt"):
            continue
        company, _, role_slug = name[:-4].partition("__")
        role = role_slug.replace("-", " ").title()
        outcome = OUTCOMES.get(company, "applied")

        with open(os.path.join(DATA, name), encoding="utf-8") as fh:
            text = fh.read()

        chunks = chunk(text)
        vectors = sb.embed(chunks)
        print(f"-- {company} / {role}: {len(chunks)} chunks", file=sys.stderr)

        print(f"""
with doc as (
  insert into jd_documents (company, role_title, outcome, raw_text)
  values ({q(company.replace('-', ' '))}, {q(role)}, {q(outcome)}, {q(text)})
  on conflict (company, role_title) do update set raw_text = excluded.raw_text
  returning id
)
insert into jd_chunks (document_id, chunk_index, content, embedding)
select doc.id, v.i, v.c, v.e::vector from doc, (values""")
        rows = []
        for i, (c, e) in enumerate(zip(chunks, vectors)):
            vec = "[" + ",".join(f"{x:.6f}" for x in e) + "]"
            rows.append(f"  ({i}, {q(c)}, {q(vec)})")
        print(",\n".join(rows))
        print("""
) as v(i, c, e)
on conflict (document_id, chunk_index) do update
  set content = excluded.content, embedding = excluded.embedding;""")


if __name__ == "__main__":
    main()
